function formatFigure(xLabel,yLabel,titleText)

set(gcf,'Color','w');

xlabel(xLabel,...
       'FontSize',14,...
       'FontWeight','bold');

ylabel(yLabel,...
       'FontSize',14,...
       'FontWeight','bold');

title(titleText,...
      'FontSize',15,...
      'FontWeight','bold');

set(gca,...
    'FontSize',13,...
    'LineWidth',1.2,...
    'Box','on');

grid on;
grid minor;

end